import { MigrationInterface, QueryRunner } from "typeorm";

export class default1678214565563 implements MigrationInterface {
    name = 'default1678214565563'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "vane_paises_novo" ("pais_id" number GENERATED BY DEFAULT AS IDENTITY, "nome_pais" varchar2(255) NOT NULL, CONSTRAINT "PK_f002fe52a35b3d8801209497fef" PRIMARY KEY ("pais_id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "vane_paises_novo"`);
    }

}
